define([], function () {
    var rtn = {
        week: [
            {text: '选择', value: undefined},
            {text: '周日', value: '1'},
            {text: '周一', value: '2'},
            {text: '周二', value: '3'},
            {text: '周三', value: '4'},
            {text: '周四', value: '5'},
            {text: '周五', value: '6'},
            {text: '周六', value: '7'},
        ],
        hour: [
            {text: '选择小时', value: undefined},
            {text: '0', value: '0'},
            {text: '1', value: '1'},
            {text: '2', value: '2'},
            {text: '3', value: '3'},
            {text: '4', value: '4'},
            {text: '5', value: '5'},
            {text: '6', value: '6'},
            {text: '7', value: '7'},
            {text: '8', value: '8'},
            {text: '9', value: '9'},
            {text: '10', value: '10'},
            {text: '11', value: '11'},
            {text: '12', value: '12'},
            {text: '13', value: '13'},
            {text: '14', value: '14'},
            {text: '15', value: '15'},
            {text: '16', value: '16'},
            {text: '17', value: '17'},
            {text: '18', value: '18'},
            {text: '19', value: '19'},
            {text: '20', value: '20'},
            {text: '21', value: '21'},
            {text: '22', value: '22'},
            {text: '23', value: '23'},
        ],
        minute: [
            {text: '选择分钟', value: undefined},
            {text: '00', value: '0'},
            {text: '05', value: '5'},
            {text: '10', value: '10'},
            {text: '15', value: '15'},
            {text: '20', value: '20'},
            {text: '25', value: '25'},
            {text: '30', value: '30'},
            {text: '35', value: '35'},
            {text: '40', value: '40'},
            {text: '45', value: '45'},
            {text: '50', value: '50'},
            {text: '55', value: '55'},
            // {text: '60', value: '60'},
        ],
    }
    return rtn;
});